### ISSUE TITLE
Can't read events from a proxy contract

### ISSUE THREAD

**Issue by krebernisak** [ethereum-optimism/go-ethereum#252]
Reading events works as expected when reading from a normal contract, but if we use a proxy contract no events are returned when querying the proxy. On the other hand, events are returned when querying the implementation contract. This is the opposite of how an EVM node behaves.

I've made [a simple project](https://github.com/krebernisak/optimism-tutorial) to demonstrate this behavior.

I've set up a simple ERC20 implementation + OZ Proxy contract:

1. Deploy ERC20 implementation contract
2. Deploy OZ Proxy using 👆 address as implementation
3. Initialize ERC20 contract using `proxy.init`
4. Make 2x Transfer using `proxy.transfer`
5. Try to read events...

Events are read using Ethers v5 and this snippet of code:

```javascript
  const _queryFilterTransfer = async (queryContract, filterContract) => {
    // Get the filter
    const filter = filterContract.filters.Transfer(null, null, null);
    // Query the filter
    return await queryContract.queryFilter(filter, 0, "latest");
  };

  // Test 1
  const logs1 = await _queryFilterTransfer(impl, impl);
  console.log(`Query{impl}  + Filter{impl}:  Expecting 0, got ${logs1.length}`);

  // Test 2
  const logs2 = await _queryFilterTransfer(impl, contract);
  console.log(`Query{impl}  + Filter{proxy}: Expecting 0, got ${logs2.length}`);

  // Test 3
  const logs3 = await _queryFilterTransfer(contract, impl);
  console.log(`Query{proxy} + Filter{impl}:  Expecting 2, got ${logs3.length}`);

  // Test 4
  const logs4 = await _queryFilterTransfer(contract, contract);
  console.log(`Query{proxy} + Filter{proxy}: Expecting 2, got ${logs4.length}`);
 ```

Testing ERC20 proxy on EVM:

```
Query{impl}  + Filter{impl}:  Expecting 0, got 0
Query{impl}  + Filter{proxy}: Expecting 0, got 0
Query{proxy} + Filter{impl}:  Expecting 2, got 2
Query{proxy} + Filter{proxy}: Expecting 2, got 2
```

Testing ERC20 proxy on OVM:

```
Query{impl}  + Filter{impl}:  Expecting 0, got 2
Query{impl}  + Filter{proxy}: Expecting 0, got 2
Query{proxy} + Filter{impl}:  Expecting 2, got 0
Query{proxy} + Filter{proxy}: Expecting 2, got 0
```

**Comment by smartcontracts** [comment]
@krebernisak sorry for the delay here. We've identified the issue and are working on a fix right now. Shouldn't be too long. Sorry about that!
