### ISSUE TITLE
Clean up start script

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/go-ethereum#272]
There have been multiple parties that don't know to set `USING_OVM=true` when starting up geth - I think we should always assume that the user intended to start up geth in OVM mode.

**Comment by tynes** [comment]
Its mentioned in the readme and is used in the start script. What is the action item here?

**Comment by K-Ho** [comment]
@tynes Would a user ever want to start up our geth fork without setting `USING_OVM=true`? Otherwise can we just remove the need for that flag?

**Comment by tynes** [comment]
The whole point of `USING_OVM` is to prevent tons of tests from breaking. Its a bit of a tradeoff

**Comment by tynes** [comment]
Closing this, feel free to reopen another issue about `USING_OVM` - i'd consider it to be tech debt
